### ISSUE TITLE
How to define the success of the docathon?

### ISSUE THREAD

**Issue by NelleV** [BIDS/docathon#10]
It'd be nice to have some measures of how successful our event has been. Here is a couple of ideas.

- Increase of number of commits of documentation?
- Number of documentation tickets closed on projects participating?
- Number of people participating?
- How trendy #docathon is on twitter?

Feel free to add comments and start a discussion about this here!

**Comment by Carreau** [comment]
I would have to have, by the end of the docathon a public document that list:

 - Best/Worst practices for documentation (followed and not followed), as well as _reasons_ why :
   - few project have rel='canonical' in their docs.
     - except Readthedocs there is no sphinx plugin to do that. 
     - it's important for google to find the right reference and not link to 5 year old documentation. 
   - you probably want to doc version switcher
     - Because people use old version of project and need to access old docs. 
   - Don't publish documentation at the root of a webside
     - After your stuck to change the scheme and get screwed if you want a /stable/ /latest/ url
 
Add to that a list of projects that currently fill needs, and what is missing. 
What are the pain points for documentation. 

I'm going to guess that without such a document the effort of the docathon will stop at the last day of the docathon. 

We can ask some project to add a `docathon` label on GH.

**Comment by choldgraf** [comment]
@NelleV do you want to edit the top-level comment with updates, or shall we just use the thread as a whole?

re: goals I think @Carreau is correct in wanting to make sure we have something tangible as a result of the docathon. A document (maybe hosted on the docathon repo/website?) is a good start.

Maybe we can also come up with some numbers for # projects contributed to, # commits, etc?

**Comment by NelleV** [comment]
I don't think the goal of the docathon is to create such a document. It may be a goal *before* the docathon to do something like this (thought I am really unsure about this and feel vastly unqualified to write such a document). For me, the goal of the docathon is to actually improve the documentation of a particular project and gain momentum in this.

**Comment by Carreau** [comment]
> and gain momentum in this

I didn't wanted to say that the document should be *the* main point, but a document that put some best practices that are easy for new contributors and can touch a wide range of project may be helpful to gather momentum.

I agree that having a summary _before_ the docathon would be helpful, but keeping it in mind _during_ the docathon and asking people to contribute to it when they come across practices/annoyances/projects/solution would be a nice thing.

**Comment by choldgraf** [comment]
I think @NelleV is correct that the primary goal of the docathon should be contributing to documentation in various projects (or building software that improves documentation etc). I also think it's good to use this as an opportunity to coalesce ideas and have a resource that lasts beyond the event (e.g. our pages for documentation tools are kind of like this already). IMO I think that it's fine to make this a sub-goal of the docathon and treat it as a "project" to be worked on during the week like any of the other projects.

**Comment by choldgraf** [comment]
Closing this since there hasn't been a ton of new discussion, and I think we have a good idea for what we're shooting for
