### ISSUE TITLE
Roadmap for the docathon

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#14]
Docathon start date: February, 19th (Sun) or 20th (Mon)
Duration: 1 week

Check out the project plan here:
https://docs.google.com/spreadsheets/d/1eOdGNHUZY6zQ8N7jHp0gWdzSLdfWmjmgl_xsEo1qXs4/edit?usp=sharing

**Comment by choldgraf** [comment]
Added you to this @NelleV in case you want to chime in. This is a high-level roadmap, shouldn't have every to-do in it, but I want to make sure that we're budgeting the right amount of time for things before the event.

**Comment by NelleV** [comment]
you are so organized…
I'll never (ever, ever, ever) tell you how we organize scipy, euroscipy and pyconfr…

**Comment by choldgraf** [comment]
haha gantt charts are great!
--
