### ISSUE TITLE
Get website running on gh-pages

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#2]
I got pelican to properly serve the website on my computer, but the gh-pages version of the site doesn't have proper links or CSS. Not sure why this is. I basically just followed the guide [here](http://docs.getpelican.com/en/3.6.3/tips.html#publishing-to-github) and pushed the `output` folder to gh-pages with `ghp-import`. Any ideas?

**Comment by NelleV** [comment]
So I think you've solved this issue. Right?

**Comment by choldgraf** [comment]
mmmm...sort of, I'm still confused trying to build pelican and last I
checked, going to the gh-pages branch on github resulted in an error...
--

**Comment by choldgraf** [comment]
I'm actually working on this now tho so maybe this'll be fixed in an hour
--

**Comment by NelleV** [comment]
That link works: https://bids.github.io/docathon/

**Comment by NelleV** [comment]
eh… worked :) (past tense)

**Comment by choldgraf** [comment]
ok I think it works again now :)

**Comment by choldgraf** [comment]
I'm closing and we can move discussion of this over to the new issue about content / structure of the site at #6
