### ISSUE TITLE
Create a when2meet to send to organizers at UCB + UW + NYC

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#20]
Doodle link here: http://doodle.com/poll/mgnmrt5w2ssztxcm

**Comment by choldgraf** [comment]
And in terms of people to contact, Ariel + Jake at UW, Stefan at NYU? @NelleV do you know the NYU folks? Do you want to send to them? I think @arokem is looking at this repo, yes?

**Comment by arokem** [comment]
I'm enjoying the conversation. 

There are a few others here who might be interested in participating: Joe Hellerstein, Valentina Staneva, Bernease Herman, Bryna Hazelton. A few of the postdocs: Rahul Biswas, Michael Beyeler, (probably some others I don't know about), Dave Beck, ... ?

**Comment by NelleV** [comment]
I take @choldgraf as a :+1: on the doodle.
I'll send it around.
