### ISSUE TITLE
Create questionnaires for projects / participants to sign up

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#24]
Here we can share / discuss the questionnaire sent out to participants. We should get this done soon so that we can make an official announcement and get people to sign up.

Maybe @NelleV and @rlbarter and @teonbrooks can work together on this? Then we can discuss at our next meeting and make an official announcement. What do you guys think?

**Comment by choldgraf** [comment]
Pinging @NelleV about this and maybe you can find other folks to help out as well?

**Comment by choldgraf** [comment]
hey @NelleV and @mrzv, where are we on the questionnaire? We should get this out there sooner than later. I can give some input as well, I just had a conversation with one of the organizers of write the docs and they sent along some links for inspiration.

**Comment by mrzv** [comment]
We are meeting about this tomorrow after the fellows lunch. If you can join, we can discuss it all together.

**Comment by choldgraf** [comment]
sounds good
--

**Comment by teonbrooks** [comment]
Hey, just saw the tag on this issue. I would like to help out :) let me know what I can do

**Comment by choldgraf** [comment]
If you wanna come say hello on Thursday it sounds like we'll chat about this then. Or you can skype in or something? Or it'll be useful for people to take a look at questions etc once there's a draft, so you can give input then as well!

**Comment by NelleV** [comment]
Maybe we should discuss about what you have in mind @choldgraf . I expected this issue to be a very straightforward two field questionnaire. Are you expected more?

**Comment by choldgraf** [comment]
I think the questionnaire will be pretty straightforward but want to make
sure we're on the same page about how we'll try to facilitate people
working on projects during the docathon (e.g., do we ask projects to have
explicit documentation challenges, do we try to pair people with projects,
or just let them choose, etc).
--

**Comment by choldgraf** [comment]
I feel like decisions about those points will inform the kinds of things we
put on the signup questionnaire. But if you think they're independent of
one another we can discuss them separately too
--

**Comment by NelleV** [comment]
I think we should for the simplest possible solution, which is then quite straightforward to implement. In particular, if we want this event to scale up, we don't want to be involved too much in stuff like pairing people and monitoring projects. Let's see what we come up with.

@mrzv Does that challenge the coffee tasting part of the meeting?

**Comment by mrzv** [comment]
I take it @NelleV's idea is "Project name", "Project URL".

@NelleV I have a feeling coffee tasting part of the meeting won't be happening tomorrow because of the rain.

**Comment by NelleV** [comment]
Yep, that was my idea, with maybe in addition:
Contact name:
Github Project URL: (such as https://github.com/matplotlib/matplotlib/projects/1)

**Comment by mrzv** [comment]
"Contact name" and "Github Project URL"?! No, that's way too complicated. ;-)

**Comment by choldgraf** [comment]
Fair point - we can discuss as a group (after the initial call has been sent out) what instructions to give to the projects / participants. Sounds good?

**Comment by choldgraf** [comment]
In that case, @teonbrooks you might wanna wait until that discussion to start chiming in etc. cool?

**Comment by NelleV** [comment]
here are the fields we are thinking of asking (fields marked with * are mandatory).

Projects
--------
- *Name
- Github Organization/URL if applicable
- *Description
- Documentation URL
- *Contact email.
- What is your goal?
   - create documentation
   - improve existing documentation
   - improve tools.
   - other?
- Project link/list of tasks
- Do you have a list of clear and well-defined tasks that attendees can work on?

"Users/attendees"
----------------------
- *Name
- Github username
 - Location
- "Team"

I am going to create a google form. We can easily add fields later if necessary.
I am also going to speak to Matplotlib core developers to set up an example of project. We can easily from the output of the google form generate a "nicely" formatted list of projects for the website.

**Comment by teonbrooks** [comment]
> In that case, @teonbrooks you might wanna wait until that discussion to start chiming in etc. cool?

sounds good

**Comment by choldgraf** [comment]
Those options sound good to me - I think we should ask for email as well for the attendees. And maybe explicitly ask "do you plan on working at BIDS during the week".

Want to throw together a google form and we can get it finalized quickly?

**Comment by choldgraf** [comment]
hey @NelleV and @mrzv , is this ready to send out? Should do this soon.

**Comment by NelleV** [comment]
Yes, here:
- Project registration page: https://docs.google.com/forms/d/e/1FAIpQLSfxdiKG0ms_zuBZiPkL9EGma1z_LsPAina4SEar7U83tJPkrQ/viewform
- User registration page:
https://docs.google.com/a/berkeley.edu/forms/d/e/1FAIpQLSchM8I47hobFX-q9TbU1pPTAm0RhthClkEGiohcXRDoYh8rfQ/viewform

**Comment by NelleV** [comment]
(Note: they are in the docathon bdrive)

**Comment by choldgraf** [comment]
think we should send 'em out tomorrow? Monday?

**Comment by mrzv** [comment]
I have permission to view the first, but not the second page. Not that I need it right now.

**Comment by NelleV** [comment]
@mrzv that should be fixed.

@choldgraf Can we have a couple of us tests those before adding a link on the website?

**Comment by mrzv** [comment]
On the user registration page, why are GitHub user name and name the same field? Let's make them two separate fields, with Github user name being optional.

**Comment by NelleV** [comment]
Fixed

**Comment by choldgraf** [comment]
just submitted two quick replies. A couple thoughts:

* For the "documentation URL link" it wasn't clear to me if we wanted to
point people to the public-facing documentation, or to the github
repository code for documentation
* For the "do you want to be notified about docathon activity" question,
maybe mention that this is like once a few months or something. Or at least
say "very occasional"
--

**Comment by NelleV** [comment]
Note: you are more than welcome to edit those

**Comment by choldgraf** [comment]
Questionnaires are now live and in the google doc
