### ISSUE TITLE
Create infrastructure for tracking metrics of docathon commits

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#3]

**Comment by Carreau** [comment]
My _guess_ is that many action will be in non-docathon repository. 
So when this is on github, one way would to ask contributors to mention this issue in the PR/commits.

**Comment by NelleV** [comment]
We're detecting commits with "DOC" in them right now.

**Comment by choldgraf** [comment]
Yeah - the hope is that we can get some projects to sign up beforehand, and then the day of in the morning we'll explain to put "DOC:" at the beginning of their commits, then we can scrape that.

**Comment by choldgraf** [comment]
@NelleV when you write some code to do this, are you going to commit it to this repo? Or are you starting a separate repo that's related to the github metrics project?

**Comment by choldgraf** [comment]
I'm closing this as a dupe of #13
