### ISSUE TITLE
Finalize website / signup form before announcing

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#30]
Hey team - @NelleV and I have finished the signup questionnaire as well as providing instructions for how other people can host docathon events at their institutions. We're planning to send out an email to MSDSE folks / twitter / etc tomorrow.

https://bids.github.io/docathon/

Can you take a look at the website etc, click on the links to forms / pages, etc, and let us know if you have any last comments or thoughts?

**feel free to open any pull requests for change you'd like to see.** Ping us on the slack channel if you'd like to chat about it / want a review.

@NelleV @stefanv @Carreau @rlbarter @kevkoy @michaelpacer @mrzv @aliferg @teonbrooks

**Comment by teonbrooks** [comment]
@choldgraf, mind inviting me to the slack. 

I just made a simple change, turned the bare urls into hyperlinks in the resources section markdown

**Comment by mrzv** [comment]
@choldgraf, we have a slack channel? I too would like an invite.

**Comment by NelleV** [comment]
We have a docathon chan on the msdse slack chanel. Are you on this one?

**Comment by mrzv** [comment]
Nope.

**Comment by NelleV** [comment]
I'm investigating how to invite you. It may take a while…

**Comment by choldgraf** [comment]
same for you @teonbrooks , we'll figure this out and then we can all partyparrot as a team

**Comment by choldgraf** [comment]
hey @teonbrooks and @mrzv, looks like you can sign up at the link I just emailed you (don't wanna post here since it's public)

**Comment by Carreau** [comment]
I clicked everywhere and couldn't break anything.

**Comment by choldgraf** [comment]
Sorry to disappoint you @Carreau  ;)
