### ISSUE TITLE
custom_inherit as a documentation tool

### ISSUE THREAD

**Issue by meowklaski** [BIDS/docathon#33]
This is a follow up from a twitter conversation.

[custom_inherit](https://github.com/meowklaski/custom_inherit) is a Python package that provides convenient, light-weight tools for inheriting/merging docstrings in customizeable ways. 

This helps facilitate thorough and consistent documentation, since documentation need not be duplicated manually when it is being "inherited". 

### Features
- A metaclass that instructs children to inherit docstrings for their attributes from their parents, using custom docstring inheritance styles. This works for all varieties of methods (instance, static, class) and properties, including abstract ones.
- A decorator that merges a string/docstring with the docstring of the decorated object using custom styles. This can decorate functions as well as all varieties of class attributes.
- Built-in docstring merging styles for popular docstring specifications (which work nicely with Sphinx):
    - [NumPy docstring specification](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard)
    - [Napoleon docstring specifications](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html#id1) (for both [Google](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google-style-python-docstrings) and [NumPy](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy) styles)
    - Merging based on [reST sections](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections)
    - Simple inheritance from a parent if the docstring is not overwritten ([deprecated in Python 3.5](https://docs.python.org/3/library/inspect.html#inspect.getdoc))
- A simple interface for using your own docstring inheritance style.
- No side effects, like obfuscating function signatures or error tracebacks. Does not affect performance. 

More details, including advanced usage examples, are provided in repo's README.

**Comment by choldgraf** [comment]
that looks pretty cool! thx for the suggestion

**Comment by choldgraf** [comment]
I'm adding a link to this issue in the tools issue (#4) so that we can pull this information when we figure out how to show off the tools etc. @meowklaski , any improvements to this tool that you've been hoping to implement? We're encouraging folks not only to work on documentation itself, but also tools for documentation during the week!

**Comment by meowklaski** [comment]
The main contributions that I could envision to `custom_inherit` are:
- Contributing additional built-in docstring inheritance styles (although I think most of the major ones are covered)
-  Refine the default styles to be more fully-fledged (e.g. more sophisticated support for reST beyond header sections.)
- Explore more edge cases in my the tests.

I definitely am open to ideas for other features/improvements!

**Comment by choldgraf** [comment]
Closing this since I'm not sure what else is actionable with it. I'd suggest adding those as ideas to the repo issues page, and maybe some work can be done during the week!
