### ISSUE TITLE
Instructions to hosts are ambiguous/wrong

### ISSUE THREAD

**Issue by arokem** [BIDS/docathon#35]
"create a pull request on our Github-hosted website, with a new file in content/pages/hosts/XX.md where XX is the name of your institute"

There is no folder called "contents". Also, clarify that PRs should be against gh-pages.

**Comment by choldgraf** [comment]
I already fixed the link to the folder: https://bids.github.io/docathon/pages/hosting.html

for the branch, it should actually be against master, I'll clarify that as well

**Comment by choldgraf** [comment]
ok check the page again - are those instructions more clear?

**Comment by choldgraf** [comment]
Closing this since I think this is fixed...feel free to reopen if more changes needed
