### ISSUE TITLE
Moving up the 1st day's schedule to begin at 10:00am

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#38]
What do you guys think about moving up the 1st day's schedule so that we begin at 10AM, have a 20 minute break in between tutorials, and end around 12:30? That would give some speakers extra time to make it since they're busy during the morning (e.g., @rlbarter). Anyone have opinions about this?

@NelleV I know you suggested some break in there so this would accommodate that too.

https://docs.google.com/spreadsheets/d/1BVzUiNUAWksf8l0lJ3WrtgY-DuGrGmJo54cdSkummlg/edit#gid=0

**Comment by NelleV** [comment]
sounds good to me.

**Comment by choldgraf** [comment]
I'll just go ahead and plan on doing this unless anybody speaks up. We can discuss at the meeting too.
