### ISSUE TITLE
Add the slack channel link to the website

### ISSUE THREAD

**Issue by NelleV** [BIDS/docathon#39]
https://docathon.herokuapp.com/

**Comment by Carreau** [comment]
Done, on the host page. Leaving open to make it more proeminent

**Comment by choldgraf** [comment]
Do you guys think it should be on a more prominent page than just for hosts? I can see arguments to both sides. Maybe we can just email out a link to people that signed up

**Comment by mrzv** [comment]
FWIW, I think hosts should be on a more prominent page than just hosts.

**Comment by NelleV** [comment]
We should at least have announcements for the different hosts.

**Comment by choldgraf** [comment]
@mrzv as in, a list on the front page?

**Comment by mrzv** [comment]
Yes, to both.

**Comment by choldgraf** [comment]
cool - I think that's a good idea. let's wait until we get some kind of confirmation from NYC and then we can have a little sidebar or something perhaps.
