### ISSUE TITLE
Pelican deprecated PAGES in favor of pages

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#42]
We discovered why the website wasn't building properly for @NelleV. It's because in 3.7 pelican deprecated the `PAGES` variable in lieu of `pages`. I believe that `pages` should work on pelican <3.7, but perhaps we should update the version of pelican that travis is using to be up-to-date?

@Carreau, we were looking for the config that you're using to handle travis but couldn't find it...could you give us a quick runthrough either in this issue or back at BIDS?

**Comment by Carreau** [comment]
> @Carreau, we were looking for the config that you're using to handle travis but couldn't find it...could you give us a quick runthrough either in this issue or back at BIDS?

Sure.
