### ISSUE TITLE
Don't understand what exactly one should/can work on during the event?

### ISSUE THREAD

**Issue by KsenyaSerova** [BIDS/docathon#58]
Can it be anything? Or is it something in particular/your projcet you want people to fork and hack on?
I just received a bunch of emails about Doathon and I have no idea what it is about :)

**Comment by choldgraf** [comment]
Hey! We're trying to keep things relatively open-ended. Mostly we just want to encourage people to contribute towards documentation in their respective worlds. However, to help with some coordination, we have [signups for projects](https://goo.gl/forms/0cPpw01zehrEyDDE3). This will let us keep track of the commit activity so we can see who's working on the docs. We've also got [signups for participants](https://goo.gl/forms/AaW2b24mMxOutxt02) where they can mention whether they'd like some guidance on a project to contribute to.

We've also got two blog posts up to give projects / participants some tips on contributing to documentation, which you can find here:

[participants](https://bids.github.io/docathon/contributing-documentation.html)
[projects](https://bids.github.io/docathon/encouraging-user-docathon.html)

does that help? and do you have any suggestions on how to modify the language on the site to be more clear? :)

**Comment by choldgraf** [comment]
We've updated the language on the website to try and be a little bit more clear
