### ISSUE TITLE
Fix the project pages build

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#63]
hey @NelleV and @Carreau, I updated the build script so that it auto inserts the images into each project page, and then moves those pages into the `pages/projects` folder. I'm not sure the best way to handle this on the Travis side of things. I need to work on some other stuff now, but can one of you take a look at the code to see how to make this go live?

**Comment by Carreau** [comment]
I'm looking at it. I've already push a few fixes, but I need to have it to completely work locally to figure out some things.

**Comment by choldgraf** [comment]
it works fine locally on my computer (e.g. I can do `make html; make serve`
and the pages pop up
--

**Comment by Carreau** [comment]
> it works fine locally on my computer (e.g. I can do `make html; make serve`
> and the pages pop up

Not on mine, exceptions get swallowed and no graph on the website.

**Comment by NelleV** [comment]
It's fixed.

**Comment by NelleV** [comment]
actually, it isn't fixed on travis, but it works fine on my computer. I'll investigate more.

**Comment by NelleV** [comment]
found out why :)

**Comment by NelleV** [comment]
https://bids.github.io/docathon/pages/projects/matplotlib.html
