### ISSUE TITLE
Define schedule for the event

### ISSUE THREAD

**Issue by choldgraf** [BIDS/docathon#7]
Right now the proposed schedule is something like:

* One week
* First day
  * Tutorials and sharing resources
  * Next, a general description of what projects are available
  * Suggest that each project creates a clear list if they want to have random users help out
* Mid week
  * Follow up email to describe how things are going.
   * Remind people to use twitter + gitter
* End of week
  * Wrap up conversation + challenges
  * Next steps after the docathon?
  * Happy hour + beer + non beer things for non beer drinkers
All week
Gitter for internal discussion
Twitter for more open conversation

**Comment by choldgraf** [comment]
@NelleV do you want to throw our "to do" list up here for us to discuss, or keep in gdocs?

**Comment by choldgraf** [comment]
actually if we wanna use github let's just create a new issue for the "to do" list and then keep this issue for planning the week itself

**Comment by NelleV** [comment]
I'll do that.

**Comment by choldgraf** [comment]
I've created a small "docathon schedule" sheet in the project plan. it's the second page in the document now, so feel free to make suggestions etc. there.
