### ISSUE TITLE
Calwpack has no graphs.

### ISSUE THREAD

**Issue by Carreau** [BIDS/docathon#77]
Unsure why. 

Need to investigate. I'll try to do that but putting that here note to forget.

**Comment by choldgraf** [comment]
It could just be that we need to re-run the build. The annoying thing is that I need to manually update the dropbox file w/ project signups on it. I'm doing this now, so re-run in like 2 minutes and we'll see if that works

**Comment by Carreau** [comment]
> It could just be that we need to re-run the build. The annoying thing is that I need to manually update the dropbox file w/ project signups on it. I'm doing this now, so re-run in like 2 minutes and we'll see if that works

Oh, can you invite me as well, I can update. I thought it was pulling from GDrive.

**Comment by choldgraf** [comment]
sadly it isn't, which is annoying. We could pull from gdrive but we'd need to get the google API auth working and I just didn't have the time to debug it, so a stupid fast solution was to dump the CSV file onto a dropbox folder, and have the python scripts download from that (public) link. I'll add you to the folder now

**Comment by Carreau** [comment]
Thanks. I've triggered a rebuild.

**Comment by choldgraf** [comment]
it failed and the log isn't loading for me. maybe an S3 problem still?

**Comment by Carreau** [comment]
> it failed and the log isn't loading for me. maybe an S3 problem still?

Likely.

**Comment by Carreau** [comment]
figured it out, some people registered 2 project (separated by commas), so download_project is not happy.

**Comment by choldgraf** [comment]
oh ho! we can just create new rows for these, ya? doesn't google forms know
anything about tidy data?!?!
--

**Comment by Carreau** [comment]
> oh ho! we can just create new rows for these, ya? doesn't google forms know
> anything about tidy data?!?!

Yeah it's done. 
Waiting for builds. 

I've figured out even with S3 down we can use `travis logs` (the ruby gem) to see the logs live.

**Comment by choldgraf** [comment]
looks like plots are updated but still no clawpack (and a few others missing) https://bids.github.io/docathon/pages/projects/projects.html

**Comment by Carreau** [comment]
They are in .downloaded_projects though.

**Comment by choldgraf** [comment]
clawpack is up there now, although it doesn't look like there's any activity in the last few days https://bids.github.io/docathon/pages/projects/clawpack.html

**Comment by choldgraf** [comment]
LMK if that doesn't look correct and we can reopen
