### ISSUE TITLE
Getting involved in organizing docathon

### ISSUE THREAD

**Issue by teonbrooks** [BIDS/docathon#8]
Hey everyone, I would like to join the organizing committee for the docathon. However I can help, let me know :)

**Comment by choldgraf** [comment]
Yeah! I'll start including you on emails about this. For now, check out the projects page for what we're working on. Want to start chiming in on issues there, or just open issues for ways you'd like to help out?

https://github.com/BIDS/docathon/projects/1

**Comment by teonbrooks** [comment]
I'm now involved! closing
