### ISSUE TITLE
Logos for supporting institutions

### ISSUE THREAD

**Issue by story645** [BIDS/docathon#82]
Logo for CUNY sponsor, which is the [Graduate Center Digital Initiatives](https://gcdi.commons.gc.cuny.edu/)

This one has all the affiliations:
![gcdi-logo10](https://cloud.githubusercontent.com/assets/1300499/23535637/9828c3e2-ff8d-11e6-98b0-d28448b09d8d.jpg)

**Comment by choldgraf** [comment]
Can people put links / images for logos for all the supporting institutions here?

@NelleV @aliferg @arokem

**Comment by choldgraf** [comment]
@story645 I took the liberty of changing the issue title, hope that's ok!

**Comment by NelleV** [comment]
I can take care of this saturday.

**Comment by choldgraf** [comment]
![bids logo acronym - color](https://cloud.githubusercontent.com/assets/1839645/23583984/b0741b00-0108-11e7-89cf-1569be96c378.png)

**Comment by choldgraf** [comment]
![msdse](https://cloud.githubusercontent.com/assets/1839645/23583987/c0f76b94-0108-11e7-95f6-a1f4162bfc41.png)

**Comment by choldgraf** [comment]
See hosts page here: https://bids.github.io/docathon/pages/hosts.html

if we can think of a better place for this, lemme know and I can move it
